# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20161103_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='start_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
