# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-12 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_paymentrecord_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='pay_status',
            field=models.TextField(default='0', max_length=5),
        ),
    ]
