# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-13 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_auto_20161112_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='card_no',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='pay_status',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
