# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-13 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_auto_20161113_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='card_no',
            field=models.IntegerField(blank=True, default=0, max_length=8, null=True),
        ),
    ]
