# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-13 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0009_auto_20161113_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='table_no',
            field=models.IntegerField(blank=True, default=0, max_length=8, null=True),
        ),
    ]
