# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0011_orderrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='member_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.PaymentRecord'),
        ),
    ]
