# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-18 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0012_auto_20170218_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
