# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-29 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0012_auto_20170521_1859'),
        ('cashier', '0014_auto_20170226_1256'),
    ]

    operations = [
    ]
