# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-29 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0015_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='cat_party',
            field=models.BooleanField(default=False),
        ),
    ]
