# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-16 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0016_paymentrecord_cat_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='price_type',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='price_type',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
